# Generated by Django 3.1 on 2020-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20200830_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timing',
            field=models.TimeField(),
        ),
    ]
