# Generated by Django 3.1 on 2020-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20200830_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timing',
            field=models.DateTimeField(default='2020-09-30T10:00:00Z'),
        ),
    ]
